[package]
name = "lsp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dirs = "5"
fd-lock = "4"
futures.workspace = true
sandbox = { path = "../sandbox" }
serde.workspace = true
serde_json.workspace = true
similar = "2"
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "process"] }
tokio-util = { version = "0.7", features = ["rt"] }
tracing = "0.1"
url = "2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
